/**
 * RFC 7807 Problem Details Error Contracts
 *
 * Standardized problem representation for HTTP API error responses.
 *
 * Remediates: LUGX-085, LUGX-119, LUGX-174
 */

import { z } from 'zod';

/**
 * Invalid parameter detail for validation errors (RFC 7807 extension)
 */
export interface ProblemDetailsInvalidParam {
  readonly name: string;
  readonly reason: string;
}

export const problemDetailsInvalidParamSchema = z.object({
  name: z.string().min(1),
  reason: z.string().min(1),
}).strict();

/**
 * RFC 7807 Problem Details Specification Contract
 */
export interface ProblemDetails {
  /** A URI reference that identifies the problem type */
  readonly type: string;
  /** A short, human-readable summary of the problem type */
  readonly title: string;
  /** The HTTP status code generated by the origin server for this occurrence */
  readonly status: number;
  /** A human-readable explanation specific to this occurrence of the problem */
  readonly detail: string;
  /** A URI reference that identifies the specific occurrence of the problem */
  readonly instance: string;
  /** Unique correlation ID for distributed request tracing */
  readonly correlationId: string;
  /** Optional backoff duration in seconds for retryable operations (e.g., 429 / 503) */
  readonly retryAfterSeconds?: number;
  /** Optional array of invalid parameters for schema validation errors */
  readonly invalidParams?: readonly ProblemDetailsInvalidParam[];
}

export const problemDetailsSchema = z.object({
  type: z.string().min(1),
  title: z.string().min(1),
  status: z.number().int().min(100).max(599),
  detail: z.string().min(1),
  instance: z.string().min(1),
  correlationId: z.string().min(1),
  retryAfterSeconds: z.number().int().nonnegative().optional(),
  invalidParams: z.array(problemDetailsInvalidParamSchema).optional(),
}).strict();

/**
 * Validates and creates a RFC 7807 Problem Details object
 */
export function createProblemDetails(params: ProblemDetails): ProblemDetails {
  return problemDetailsSchema.parse(params);
}
